In [2]:
import numpy as np

In [3]:
np.__version__

'2.3.1'

## Create & Read

### 1D Array

In [4]:
arr1=np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [5]:
type(arr1)

numpy.ndarray

In [6]:
arr1.shape

(5,)

In [7]:
arr1.ndim

1

In [8]:
arr1.size

5

### 2D Array

In [9]:
arr2=np.array([[1,4,5],[2,3,7]])
arr2

array([[1, 4, 5],
       [2, 3, 7]])

In [10]:
arr2.ndim

2

In [11]:
arr2.shape #Row Col

(2, 3)

### 3D Array

In [12]:
arr3=np.array([[[1,2,3],[2,3,4]],[[2,3,1],[8,9,4]]])
arr3

array([[[1, 2, 3],
        [2, 3, 4]],

       [[2, 3, 1],
        [8, 9, 4]]])

In [13]:
arr3.ndim

3

### Create Random Array

In [14]:
randomArr=np.random.rand(3,2,3)
randomArr


array([[[0.19903786, 0.54782889, 0.90684905],
        [0.34359719, 0.47357598, 0.72630349]],

       [[0.06511284, 0.42027244, 0.43766563],
        [0.76192581, 0.00992968, 0.77483393]],

       [[0.69698027, 0.84397596, 0.40512593],
        [0.37491788, 0.58426438, 0.63696149]]])

In [16]:
zeros=np.zeros((3,2,3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [17]:
full=np.full((3,2,3),9)
full

array([[[9, 9, 9],
        [9, 9, 9]],

       [[9, 9, 9],
        [9, 9, 9]],

       [[9, 9, 9],
        [9, 9, 9]]])

In [18]:
full[0]

array([[9, 9, 9],
       [9, 9, 9]])

In [19]:
full[0][1]

array([9, 9, 9])

### Update & Delete 

In [20]:
a1=np.random.rand(2,3,2)
a2=np.random.rand(2,3,2)

In [21]:
a1

array([[[0.51284149, 0.63944393],
        [0.70243081, 0.55168465],
        [0.36011788, 0.77895842]],

       [[0.88310844, 0.00287668],
        [0.74236846, 0.14534   ],
        [0.97960325, 0.98326394]]])

In [22]:
a2

array([[[0.85011287, 0.3222664 ],
        [0.4512024 , 0.52706464],
        [0.22249363, 0.36028508]],

       [[0.34121013, 0.0795644 ],
        [0.97683902, 0.87785066],
        [0.01109963, 0.54992698]]])

In [23]:
np.add(a1,a2)

array([[[1.36295436, 0.96171033],
        [1.15363321, 1.07874929],
        [0.58261151, 1.1392435 ]],

       [[1.22431857, 0.08244108],
        [1.71920747, 1.02319066],
        [0.99070288, 1.53319092]]])

In [25]:
np.subtract(a1,a2)

array([[[-0.33727137,  0.31717753],
        [ 0.2512284 ,  0.02462002],
        [ 0.13762425,  0.41867334]],

       [[ 0.5418983 , -0.07668773],
        [-0.23447056, -0.73251066],
        [ 0.96850362,  0.43333696]]])

In [28]:
np.multiply(a1,a2)

array([[[4.35973154e-01, 2.06071295e-01],
        [3.16938467e-01, 2.90773473e-01],
        [8.01239349e-02, 2.80647094e-01]],

       [[3.01325547e-01, 2.28881238e-04],
        [7.25174473e-01, 1.27586816e-01],
        [1.08732334e-02, 5.40723369e-01]]])

In [29]:
full[0][1][0]=5
full

array([[[9, 9, 9],
        [5, 9, 9]],

       [[9, 9, 9],
        [9, 9, 9]],

       [[9, 9, 9],
        [9, 9, 9]]])